[project]
name = "statistician"
version = "0.1.0"
authors = [
  { name="Marco Zausch", email="marcoz@posteo.de" },
]
description = "Package simplifying Statistical tests"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/MaCoZu/statistician"
Issues = "https://github.com/MaCoZu/statistician/issues"